#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/video/background_segm.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui.hpp"
#include <iostream>

using namespace cv;
using namespace std;

int main(int argc, char const *argv[])
{
    VideoCapture cap(0); // open the default camera
    if(!cap.isOpened())  // check if we succeeded
        return -1;

   BackgroundSubtractorMOG2 mog2;

    Mat edges;
    Mat frame;

    Mat fgMaskMOG; //foreground mask generated by MOG method

    for(;;)
    {
        cap >> frame; // get a new frame from camera
        mog2(frame, fgMaskMOG);
        imshow("fram", fgMaskMOG);
        if(waitKey(30) >= 0) break; //exit on some key
    }

	
	return 0;
}